### ISSUE TITLE
add command not parsed correctly

### ISSUE THREAD

**Issue by valerietanhx** [AY2223S2-CS2103-W17-2/tp#107]
![telegram-cloud-photo-size-5-6122731281134499084-y](https://user-images.githubusercontent.com/110474344/227720378-14d09693-a9b2-4809-bbbb-3b374fe82a5a.jpg)

the person named Test in the DHT currently has age 23, while the add command's Test is age 22, so should not be marked as duplicate

occurs with other attributes as well, e.g. different postal:

<img width="604" alt="Screenshot 2023-03-25 at 9 35 10 PM" src="https://user-images.githubusercontent.com/110474344/227720432-1a87b93d-7a49-4394-ab75-d13d07bbd690.png">

**Comment by sumhungyee** [comment]
done
