### ISSUE TITLE
[PE-D][Tester A] Postal code not existent

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-2/tp#212]
![Screenshot 2023-03-31 at 2.58.46 PM.png](https://raw.githubusercontent.com/CedricPei/ped/main/files/f7e21615-cad0-4078-8b2e-cd2be95435fc.png)

postal code 119999 is not existent in Singapore, but it is valid for the application.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: CedricPei/ped#11

**Comment by markusyeo** [comment]
We only check for postal regions i.e. first 2 digits and do not keep a map of every single postal code in Singapore as that is infeasible
