### ISSUE TITLE
[PE-D][Tester E] Able to add person with name beginning with space 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-2/tp#227]
![Screenshot 2023-03-31 at 10.24.27 PM.png](https://raw.githubusercontent.com/zuohui48/ped/main/files/94e634c5-848d-4206-afb0-55e2c93d24f3.png)
 
![Screenshot 2023-03-31 at 10.25.22 PM.png](https://raw.githubusercontent.com/zuohui48/ped/main/files/afbd26e5-8225-4002-bd40-813faf928aae.png)

I was able to add a new person with name beginning with spaces, although the UG stated that the first character cannot be a whitespace.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zuohui48/ped#11

**Comment by sumhungyee** [comment]
Intended functionality: UG updated in #175
